use super::Word;

pub fn get(index: usize) -> [&'static str; 2] {
    ANSWER_PAIRS[index].clone()
}

pub const ANSWER_PAIRS: [[&str; 2]; 1000] = [
    ["ditto", "apple"],
    ["panic", "meter"],
    ["roach", "queen"],
    ["dread", "spoil"],
    ["pinch", "straw"],
    ["leafy", "vomit"],
    ["rapid", "money"],
    ["fling", "coach"],
    ["small", "tribe"],
    ["tweed", "brush"],
    ["nylon", "grasp"],
    ["ditch", "purge"],
    ["moody", "shark"],
    ["lyric", "dough"],
    ["trace", "blink"],
    ["lousy", "tract"],
    ["taste", "glory"],
    ["expel", "gamma"],
    ["close", "bunny"],
    ["shady", "orbit"],
    ["juror", "tally"],
    ["steep", "quail"],
    ["nasal", "motor"],
    ["mimic", "feast"],
    ["loyal", "surge"],
    ["older", "fight"],
    ["nancy", "lodge"],
    ["gamma", "bunny"],
    ["under", "basic"],
    ["loose", "attic"],
    ["sinus", "hoard"],
    ["petty", "claim"],
    ["loyal", "mucus"],
    ["lunar", "kitty"],
    ["cross", "hyena"],
    ["atlas", "pouch"],
    ["taboo", "fugue"],
    ["loved", "truth"],
    ["diode", "mural"],
    ["stalk", "proud"],
    ["fence", "troop"],
    ["laugh", "probe"],
    ["tasty", "cliff"],
    ["rocky", "plane"],
    ["gross", "fifth"],
    ["daddy", "point"],
    ["whale", "broom"],
    ["haunt", "cello"],
    ["gamer", "booty"],
    ["motor", "villa"],
    ["tidal", "force"],
    ["civic", "dryer"],
    ["shaft", "comic"],
    ["triad", "goose"],
    ["panic", "towel"],
    ["liver", "spasm"],
    ["these", "daily"],
    ["ghost", "rider"],
    ["renew", "tacit"],
    ["tooth", "clean"],
    ["smell", "dirty"],
    ["seven", "fifth"],
    ["braid", "comet"],
    ["snout", "rapid"],
    ["blush", "wreck"],
    ["cling", "derby"],
    ["expel", "vomit"],
    ["small", "brick"],
    ["swell", "nifty"],
    ["mummy", "filth"],
    ["sunny", "beach"],
    ["visit", "whole"],
    ["night", "dream"],
    ["skill", "chant"],
    ["speed", "limit"],
    ["jolly", "giant"],
    ["brawl", "fight"],
    ["sweet", "candy"],
    ["glove", "wharf"],
    ["black", "unity"],
    ["start", "begin"],
    ["assay", "touch"],
    ["child", "money"],
    ["sheen", "pluck"],
    ["drawn", "glyph"],
    ["bring", "shave"],
    ["ninth", "guess"],
    ["mouth", "grass"],
    ["think", "prove"],
    ["knock", "amply"],
    ["pride", "month"],
    ["arson", "dimly"],
    ["quick", "horse"],
    ["scope", "awful"],
    ["turbo", "snail"],
    ["parch", "index"],
    ["squad", "irony"],
    ["union", "spasm"],
    ["noisy", "eater"],
    ["bulky", "draft"],
    ["optic", "glass"],
    ["spike", "notch"],
    ["climb", "spend"],
    ["watch", "movie"],
    ["vocal", "beset"],
    ["dusty", "apple"],
    ["royal", "queen"],
    ["login", "fewer"],
    ["heart", "sound"],
    ["piano", "smelt"],
    ["camel", "bison"],
    ["tribe", "snuff"],
    ["stuff", "weird"],
    ["grime", "clank"],
    ["stony", "rapid"],
    ["spice", "ought"],
    ["annoy", "giver"],
    ["exile", "bosom"],
    ["voice", "array"],
    ["pouch", "rinse"],
    ["scene", "hilly"],
    ["ample", "witty"],
    ["tough", "arise"],
    ["rigor", "abyss"],
    ["piano", "bless"],
    ["lover", "swift"],
    ["green", "salad"],
    ["rusty", "comma"],
    ["plume", "tight"],
    ["shout", "dryer"],
    ["muddy", "rhino"],
    ["baker", "touch"],
    ["colon", "assay"],
    ["patch", "quill"],
    ["ninja", "shell"],
    ["shoot", "leave"],
    ["abide", "slump"],
    ["knife", "sharp"],
    ["stoic", "algae"],
    ["point", "guard"],
    ["glaze", "thorn"],
    ["doubt", "alien"],
    ["guild", "ether"],
    ["fancy", "spell"],
    ["storm", "bland"],
    ["toxic", "grape"],
    ["showy", "quail"],
    ["dozen", "vista"],
    ["magma", "drink"],
    ["stock", "lying"],
    ["drone", "still"],
    ["float", "music"],
    ["mount", "essay"],
    ["grove", "bluff"],
    ["radar", "pilot"],
    ["grail", "tense"],
    ["cupid", "arrow"],
    ["floor", "hinge"],
    ["octal", "nerdy"],
    ["levee", "oasis"],
    ["ahead", "torso"],
    ["haste", "mourn"],
    ["hurry", "pasta"],
    ["snake", "twirl"],
    ["husky", "vicar"],
    ["comic", "guard"],
    ["alibi", "photo"],
    ["brass", "tempo"],
    ["jumpy", "scare"],
    ["leggy", "afoot"],
    ["smoky", "digit"],
    ["quark", "field"],
    ["kabob", "grill"],
    ["whale", "mummy"],
    ["ankle", "wrist"],
    ["lunch", "break"],
    ["quite", "savvy"],
    ["apnea", "blurb"],
    ["quiet", "hobby"],
    ["goofy", "inane"],
    ["paris", "hotel"],
    ["sushi", "plate"],
    ["solid", "water"],
    ["chess", "board"],
    ["dwarf", "comet"],
    ["frail", "knock"],
    ["stick", "flame"],
    ["muted", "color"],
    ["flips", "queue"],
    ["story", "fable"],
    ["mamma", "dewed"],
    ["curve", "blown"],
    ["slash", "pivot"],
    ["grace", "bunny"],
    ["deity", "shrug"],
    ["bunch", "modem"],
    ["scrub", "email"],
    ["smash", "tenor"],
    ["sweep", "login"],
    ["means", "dough"],
    ["timer", "hands"],
    ["cloud", "steam"],
    ["claim", "shout"],
    ["manta", "glide"],
    ["jelly", "sting"],
    ["jelly", "donut"],
    ["creak", "howls"],
    ["magic", "spell"],
    ["prank", "ghost"],
    ["chill", "spook"],
    ["devil", "ghost"],
    ["which", "mommy"],
    ["shiny", "armor"],
    ["candy", "sweet"],
    ["acorn", "stump"],
    ["mouse", "plant"],
    ["sonic", "grate"],
    ["round", "table"],
    ["forty", "seven"],
    ["fluff", "water"],
    ["bayou", "eerie"],
    ["touch", "grass"],
    ["crook", "nanny"],
    ["kazoo", "strum"],
    ["final", "quest"],
    ["night", "karma"],
    ["eagle", "finch"],
    ["light", "saber"],
    ["water", "build"],
    ["index", "arrow"],
    ["where", "socks"],
    ["dance", "flirt"],
    ["skunk", "aroma"],
    ["ivory", "leans"],
    ["hedge", "prick"],
    ["camel", "widow"],
    ["peeve", "annoy"],
    ["awake", "boost"],
    ["thank", "gorge"],
    ["toast", "grill"],
    ["climb", "notes"],
    ["ninja", "shred"],
    ["money", "talks"],
    ["lance", "fight"],
    ["cheer", "goals"],
    ["putty", "goose"],
    ["human", "error"],
    ["pizza", "dough"],
    ["windy", "storm"],
    ["joker", "laugh"],
    ["fishy", "place"],
    ["blank", "guess"],
    ["paper", "dolls"],
    ["black", "widow"],
    ["apple", "crumb"],
    ["smile", "frown"],
    ["trust", "money"],
    ["value", "goods"],
    ["wrist", "clock"],
    ["chirp", "tweet"],
    ["chick", "brood"],
    ["flock", "avian"],
    ["final", "words"],
    ["guilt", "sorry"],
    ["solar", "event"],
    ["blink", "stare"],
    ["snowy", "dream"],
    ["laugh", "merry"],
    ["gifts", "under"],
    ["dance", "shout"],
    ["poppy", "bread"],
    ["hello", "kitty"],
    ["sweet", "child"],
    ["aroma", "spice"],
    ["forty", "winks"],
    ["polka", "river"],
    ["power", "buggy"],
    ["ninth", "dwarf"],
    ["think", "small"],
    ["count", "sheep"],
    ["fuzzy", "warms"],
    ["wharf", "ledge"],
    ["codes", "plain"],
    ["world", "magic"],
    ["fatal", "error"],
    ["minus", "cloth"],
    ["pause", "think"],
    ["itchy", "fleas"],
    ["cache", "troll"],
    ["inbox", "draft"],
    ["rusty", "oxide"],
    ["prism", "cloud"],
    ["bushy", "plant"],
    ["apron", "sweet"],
    ["quack", "bones"],
    ["speak", "truth"],
    ["peony", "quail"],
    ["lindy", "strut"],
    ["taxes", "crook"],
    ["judge", "trial"],
    ["flash", "optic"],
    ["moldy", "fungi"],
    ["bored", "stiff"],
    ["quoth", "raven"],
    ["rocky", "blues"],
    ["brown", "meats"],
    ["lover", "giddy"],
    ["purse", "kitty"],
    ["tithe", "blood"],
    ["jelly", "honor"],
    ["spook", "agent"],
    ["thing", "place"],
    ["flood", "swamp"],
    ["shoot", "fudge"],
    ["vines", "rumor"],
    ["cynic", "doubt"],
    ["prick", "blood"],
    ["sound", "alike"],
    ["magic", "boxes"],
    ["teach", "young"],
    ["sonic", "heart"],
    ["human", "robot"],
    ["tight", "clasp"],
    ["adieu", "nymph"],
    ["peony", "lilac"],
    ["beach", "sport"],
    ["hands", "pivot"],
    ["level", "synth"],
    ["pride", "sloth"],
    ["queue", "strip"],
    ["magic", "flute"],
    ["dusty", "baker"],
    ["sinus", "fever"],
    ["maybe", "split"],
    ["tuner", "shack"],
    ["quote", "lyric"],
    ["joins", "party"],
    ["cough", "ailed"],
    ["tulip", "oxeye"],
    ["chaff", "group"],
    ["rainy", "flood"],
    ["looks", "empty"],
    ["fight", "boxer"],
    ["mined", "craft"],
    ["pulpy", "drink"],
    ["raise", "bluff"],
    ["mochi", "sakes"],
    ["hound", "speak"],
    ["words", "plaza"],
    ["buggy", "world"],
    ["dwarf", "gnome"],
    ["axiom", "guess"],
    ["jewel", "topaz"],
    ["lacks", "teeth"],
    ["climb", "tower"],
    ["meaty", "chili"],
    ["music", "party"],
    ["pinky", "thumb"],
    ["field", "scrum"],
    ["windy", "solar"],
    ["eerie", "spook"],
    ["phone", "click"],
    ["icing", "plays"],
    ["focus", "drive"],
    ["river", "south"],
    ["swamp", "berry"],
    ["rhyme", "canal"],
    ["shall", "court"],
    ["shelf", "cargo"],
    ["hotly", "brave"],
    ["forty", "valve"],
    ["plaza", "windy"],
    ["strip", "along"],
    ["dairy", "count"],
    ["sense", "logic"],
    ["kneel", "squad"],
    ["dwarf", "lobby"],
    ["digit", "slack"],
    ["groom", "windy"],
    ["snuff", "delay"],
    ["drive", "stalk"],
    ["dodge", "smash"],
    ["flush", "boxer"],
    ["cubic", "sloop"],
    ["noise", "buddy"],
    ["chick", "owner"],
    ["maxim", "blond"],
    ["snake", "fluid"],
    ["aptly", "rigid"],
    ["least", "rumor"],
    ["trash", "vigil"],
    ["robot", "helix"],
    ["avian", "model"],
    ["chunk", "great"],
    ["shift", "blood"],
    ["breed", "final"],
    ["couch", "salad"],
    ["excel", "widow"],
    ["array", "glide"],
    ["crave", "wound"],
    ["giddy", "shaft"],
    ["wharf", "mimic"],
    ["cross", "valve"],
    ["stiff", "uncle"],
    ["spore", "blind"],
    ["merry", "sight"],
    ["straw", "given"],
    ["crack", "seven"],
    ["raise", "motto"],
    ["worth", "pedal"],
    ["fight", "rouse"],
    ["thorn", "famed"],
    ["point", "amuse"],
    ["motor", "fully"],
    ["smile", "young"],
    ["toxic", "genre"],
    ["fancy", "helix"],
    ["aptly", "forge"],
    ["tying", "drake"],
    ["spill", "ahead"],
    ["award", "envoy"],
    ["river", "clump"],
    ["delay", "honor"],
    ["larva", "money"],
    ["cheek", "sound"],
    ["wheat", "comic"],
    ["fuzzy", "gamma"],
    ["femur", "paddy"],
    ["inlet", "board"],
    ["pouch", "aisle"],
    ["joint", "dummy"],
    ["stoop", "gauze"],
    ["sieve", "oddly"],
    ["offer", "catch"],
    ["enter", "godly"],
    ["upset", "logic"],
    ["bound", "sixth"],
    ["worry", "plumb"],
    ["weary", "clock"],
    ["trans", "plume"],
    ["oddly", "batch"],
    ["squid", "cater"],
    ["grate", "colon"],
    ["shawl", "every"],
    ["daily", "photo"],
    ["berry", "onion"],
    ["sunny", "comet"],
    ["verge", "dolly"],
    ["opium", "naked"],
    ["woody", "basin"],
    ["maxim", "entry"],
    ["press", "allow"],
    ["poppy", "crawl"],
    ["float", "recur"],
    ["digit", "shame"],
    ["cargo", "shell"],
    ["hound", "berry"],
    ["comma", "guess"],
    ["tenth", "parry"],
    ["wound", "legal"],
    ["smoky", "graze"],
    ["large", "mound"],
    ["femur", "gloss"],
    ["larva", "empty"],
    ["verge", "photo"],
    ["while", "scrub"],
    ["libel", "catch"],
    ["white", "drama"],
    ["triad", "hello"],
    ["baron", "mimic"],
    ["deity", "punch"],
    ["thorn", "quail"],
    ["giant", "rumor"],
    ["locus", "radar"],
    ["shaft", "world"],
    ["skull", "torch"],
    ["muddy", "glass"],
    ["shake", "color"],
    ["heave", "worry"],
    ["surge", "hitch"],
    ["valid", "nurse"],
    ["bulge", "today"],
    ["squad", "twice"],
    ["orbit", "shady"],
    ["ridge", "lunch"],
    ["snowy", "fetch"],
    ["force", "skill"],
    ["adobe", "incur"],
    ["extra", "plumb"],
    ["creek", "await"],
    ["dirty", "bacon"],
    ["renew", "hotly"],
    ["aging", "scope"],
    ["mount", "rabbi"],
    ["proxy", "tight"],
    ["stack", "gorge"],
    ["salty", "finch"],
    ["tenet", "daisy"],
    ["fling", "trash"],
    ["delta", "bison"],
    ["motor", "awful"],
    ["thing", "lover"],
    ["swine", "torah"],
    ["sloop", "dummy"],
    ["humid", "atlas"],
    ["metro", "shiny"],
    ["check", "stain"],
    ["proud", "tenet"],
    ["boxer", "smash"],
    ["going", "latex"],
    ["fleet", "sorry"],
    ["their", "loyal"],
    ["brink", "swell"],
    ["magic", "hover"],
    ["event", "color"],
    ["queue", "charm"],
    ["helix", "proud"],
    ["amiss", "lofty"],
    ["rural", "scope"],
    ["adopt", "giver"],
    ["bunny", "civic"],
    ["robin", "essay"],
    ["count", "valid"],
    ["lying", "reach"],
    ["berry", "onion"],
    ["thyme", "slick"],
    ["crime", "shady"],
    ["sunny", "welch"],
    ["sleep", "yacht"],
    ["karma", "spite"],
    ["count", "grill"],
    ["dizzy", "evoke"],
    ["crook", "guise"],
    ["inset", "proud"],
    ["bloom", "inert"],
    ["juice", "shawl"],
    ["cloak", "dryer"],
    ["angel", "truck"],
    ["click", "stead"],
    ["attic", "dryer"],
    ["fuzzy", "blend"],
    ["child", "paper"],
    ["fitch", "plane"],
    ["maple", "burst"],
    ["wedge", "scalp"],
    ["goose", "fritz"],
    ["lodge", "crack"],
    ["climb", "store"],
    ["larva", "shine"],
    ["drunk", "teach"],
    ["dread", "chunk"],
    ["batch", "messy"],
    ["dwarf", "sense"],
    ["graph", "ozone"],
    ["forum", "panic"],
    ["audit", "speck"],
    ["boxer", "imply"],
    ["witty", "bench"],
    ["folly", "hatch"],
    ["brisk", "melon"],
    ["chill", "study"],
    ["avail", "juror"],
    ["chute", "snail"],
    ["giddy", "spell"],
    ["mount", "rifle"],
    ["stony", "liver"],
    ["truth", "vigil"],
    ["billy", "undue"],
    ["vinyl", "mucus"],
    ["datum", "jolly"],
    ["snowy", "carve"],
    ["jewel", "manor"],
    ["gauze", "shift"],
    ["elude", "saint"],
    ["tidal", "serve"],
    ["river", "booth"],
    ["pitch", "bloom"],
    ["login", "shear"],
    ["elbow", "manic"],
    ["glide", "punch"],
    ["peace", "build"],
    ["roach", "ledge"],
    ["serum", "faith"],
    ["glove", "chart"],
    ["nymph", "libel"],
    ["seize", "mamma"],
    ["bring", "palsy"],
    ["widow", "tract"],
    ["chick", "bunny"],
    ["sixty", "crank"],
    ["owner", "faith"],
    ["music", "whale"],
    ["exist", "bacon"],
    ["prior", "exact"],
    ["algae", "shock"],
    ["candy", "vigil"],
    ["hatch", "wield"],
    ["miner", "bulky"],
    ["clump", "heart"],
    ["dying", "wheel"],
    ["folly", "track"],
    ["rough", "alien"],
    ["onset", "braid"],
    ["oddly", "music"],
    ["align", "etude"],
    ["shall", "brood"],
    ["tight", "juror"],
    ["aback", "dryer"],
    ["treat", "lunch"],
    ["dummy", "solar"],
    ["laden", "syrup"],
    ["debit", "groom"],
    ["silky", "watch"],
    ["arrow", "edict"],
    ["aging", "sleek"],
    ["mummy", "sense"],
    ["dizzy", "false"],
    ["gleam", "pound"],
    ["wrist", "magma"],
    ["shift", "amply"],
    ["bless", "tonic"],
    ["knock", "guild"],
    ["urine", "batch"],
    ["index", "slash"],
    ["saint", "queue"],
    ["house", "avail"],
    ["freak", "lunch"],
    ["aloud", "witty"],
    ["elegy", "fifth"],
    ["grind", "squat"],
    ["there", "flood"],
    ["ivory", "awake"],
    ["spine", "about"],
    ["chaos", "drill"],
    ["nasty", "floor"],
    ["basic", "hedge"],
    ["demon", "trial"],
    ["stick", "humor"],
    ["cubic", "plant"],
    ["gloss", "beard"],
    ["three", "vigil"],
    ["rally", "choke"],
    ["scarf", "deity"],
    ["shout", "crack"],
    ["carve", "bulky"],
    ["organ", "quite"],
    ["grand", "welch"],
    ["aware", "cloud"],
    ["rusty", "avail"],
    ["robot", "spicy"],
    ["humid", "expel"],
    ["baron", "cleft"],
    ["allow", "crime"],
    ["lurid", "showy"],
    ["rabbi", "dodge"],
    ["think", "gauge"],
    ["touch", "large"],
    ["gamma", "offer"],
    ["grief", "colon"],
    ["habit", "owner"],
    ["etude", "manor"],
    ["sloop", "ranch"],
    ["grail", "spend"],
    ["horde", "sunny"],
    ["hello", "funny"],
    ["idiot", "cease"],
    ["stoic", "valve"],
    ["seize", "crack"],
    ["build", "those"],
    ["juror", "these"],
    ["plaza", "nerve"],
    ["brunt", "logic"],
    ["azure", "toxic"],
    ["slick", "wound"],
    ["ranch", "dwell"],
    ["grove", "alias"],
    ["stoop", "revue"],
    ["nymph", "stair"],
    ["pious", "alter"],
    ["rainy", "teeth"],
    ["dummy", "alike"],
    ["mouth", "leafy"],
    ["avian", "exert"],
    ["avail", "epoch"],
    ["groan", "deity"],
    ["beset", "mimic"],
    ["rabbi", "ensue"],
    ["chuck", "drama"],
    ["fetal", "punch"],
    ["venom", "chili"],
    ["clock", "abuse"],
    ["shock", "fiber"],
    ["chuck", "torso"],
    ["vowel", "punch"],
    ["bunch", "model"],
    ["axiom", "dusty"],
    ["dough", "berry"],
    ["graph", "until"],
    ["lodge", "parry"],
    ["phase", "floor"],
    ["etude", "aroma"],
    ["camel", "booty"],
    ["light", "mason"],
    ["orbit", "naval"],
    ["palsy", "motor"],
    ["syrup", "below"],
    ["award", "cheek"],
    ["while", "spark"],
    ["winch", "grape"],
    ["again", "shock"],
    ["gloom", "inner"],
    ["write", "vodka"],
    ["expel", "chasm"],
    ["salad", "money"],
    ["birth", "annex"],
    ["clean", "fruit"],
    ["shame", "kitty"],
    ["valet", "round"],
    ["expel", "stack"],
    ["wrath", "pound"],
    ["perch", "solid"],
    ["renew", "scoop"],
    ["speck", "flint"],
    ["below", "crazy"],
    ["screw", "idiom"],
    ["worse", "light"],
    ["never", "hobby"],
    ["milky", "canoe"],
    ["fungi", "roach"],
    ["snuff", "razor"],
    ["width", "canoe"],
    ["chute", "arbor"],
    ["truss", "niche"],
    ["boost", "creep"],
    ["flame", "showy"],
    ["clamp", "brush"],
    ["taint", "slump"],
    ["snuff", "evoke"],
    ["truth", "lemon"],
    ["annoy", "budge"],
    ["admit", "funny"],
    ["baton", "equip"],
    ["mourn", "slack"],
    ["dummy", "chest"],
    ["major", "beset"],
    ["heavy", "occur"],
    ["quart", "nymph"],
    ["sauce", "folly"],
    ["chalk", "stump"],
    ["bland", "quiet"],
    ["buyer", "villa"],
    ["linen", "rocky"],
    ["inert", "lousy"],
    ["opera", "snuff"],
    ["novel", "crash"],
    ["booth", "venus"],
    ["cabin", "shoot"],
    ["cubic", "prone"],
    ["reuse", "holly"],
    ["dodge", "waist"],
    ["happy", "bound"],
    ["batch", "prose"],
    ["windy", "pause"],
    ["plaza", "round"],
    ["olive", "daddy"],
    ["arbor", "husky"],
    ["humor", "align"],
    ["grand", "sweep"],
    ["tying", "breed"],
    ["fleet", "brown"],
    ["steep", "unify"],
    ["widow", "angel"],
    ["demon", "rabbi"],
    ["spake", "dummy"],
    ["prior", "latex"],
    ["stony", "wafer"],
    ["bleed", "vapor"],
    ["blond", "spare"],
    ["avail", "broth"],
    ["scrub", "maxim"],
    ["thorn", "flake"],
    ["siege", "honor"],
    ["thigh", "enemy"],
    ["glass", "curry"],
    ["fauna", "idiot"],
    ["tunic", "valve"],
    ["bloom", "cedar"],
    ["south", "mixer"],
    ["molar", "swine"],
    ["party", "logic"],
    ["fauna", "third"],
    ["civic", "eater"],
    ["bring", "flash"],
    ["frost", "apple"],
    ["money", "guilt"],
    ["chalk", "fetus"],
    ["click", "board"],
    ["torso", "alley"],
    ["hotly", "amiss"],
    ["assay", "tweed"],
    ["glove", "hairy"],
    ["kappa", "civic"],
    ["wrist", "block"],
    ["align", "every"],
    ["tacit", "sever"],
    ["trust", "valve"],
    ["proud", "wheel"],
    ["width", "false"],
    ["tacit", "frown"],
    ["chalk", "spoon"],
    ["unfit", "groom"],
    ["armor", "yield"],
    ["draft", "shiny"],
    ["hurry", "sable"],
    ["still", "crude"],
    ["youth", "dwell"],
    ["tweed", "bunny"],
    ["level", "wight"],
    ["nymph", "trait"],
    ["child", "rusty"],
    ["serum", "baton"],
    ["algae", "torch"],
    ["mommy", "again"],
    ["knoll", "eater"],
    ["vomit", "shear"],
    ["watch", "money"],
    ["frock", "medal"],
    ["fitch", "wound"],
    ["puppy", "tenet"],
    ["await", "fresh"],
    ["bring", "jewel"],
    ["blond", "hasty"],
    ["drain", "bully"],
    ["white", "lorry"],
    ["trunk", "wheel"],
    ["large", "stock"],
    ["vicar", "bonus"],
    ["visit", "comma"],
    ["shiny", "relax"],
    ["envoy", "salad"],
    ["triad", "locus"],
    ["shear", "tying"],
    ["grand", "bluff"],
    ["spade", "witty"],
    ["hotel", "mucus"],
    ["hairy", "smelt"],
    ["civic", "super"],
    ["hatch", "rumor"],
    ["video", "match"],
    ["spine", "cloud"],
    ["stoic", "lymph"],
    ["brace", "folly"],
    ["filth", "gorge"],
    ["bluff", "satin"],
    ["mimic", "freak"],
    ["young", "spill"],
    ["satin", "globe"],
    ["quick", "gloom"],
    ["gleam", "sunny"],
    ["gamma", "shirt"],
    ["click", "motor"],
    ["exist", "frank"],
    ["clump", "deter"],
    ["raven", "midst"],
    ["vinyl", "occur"],
    ["blame", "couch"],
    ["drove", "clash"],
    ["mucus", "print"],
    ["grave", "motif"],
    ["slick", "aware"],
    ["guild", "ester"],
    ["total", "seize"],
    ["bluff", "since"],
    ["shoot", "graze"],
    ["aback", "fiery"],
    ["which", "nerve"],
    ["frown", "light"],
    ["twist", "crave"],
    ["vodka", "eight"],
    ["batch", "slope"],
    ["fight", "smell"],
    ["franc", "mouse"],
    ["vomit", "shank"],
    ["dying", "stole"],
    ["milky", "otter"],
    ["lance", "juror"],
    ["taint", "wreck"],
    ["field", "wrath"],
    ["shady", "unite"],
    ["thigh", "scrub"],
    ["flock", "wight"],
    ["dryer", "final"],
    ["theft", "sword"],
    ["agree", "smoky"],
    ["panic", "broom"],
    ["shake", "folly"],
    ["moist", "fully"],
    ["aware", "tight"],
    ["ditto", "clear"],
    ["cello", "squid"],
    ["derby", "toxin"],
    ["proof", "debut"],
    ["music", "depth"],
    ["tunic", "royal"],
    ["whose", "plump"],
    ["funny", "kappa"],
    ["booth", "purse"],
    ["third", "spell"],
    ["feast", "bulky"],
    ["lowly", "aside"],
    ["visit", "gauze"],
    ["ethic", "groan"],
    ["their", "small"],
    ["house", "grain"],
    ["clamp", "enjoy"],
    ["exalt", "bunny"],
    ["kneel", "motto"],
    ["broth", "snack"],
    ["jolly", "reuse"],
    ["crane", "thigh"],
    ["burst", "wagon"],
    ["sting", "delay"],
    ["mound", "birch"],
    ["drive", "lymph"],
    ["drove", "chuck"],
    ["scoop", "bluff"],
    ["brook", "cheap"],
    ["adopt", "bliss"],
    ["creed", "lotus"],
    ["major", "shine"],
    ["notch", "amply"],
    ["theme", "cigar"],
    ["brave", "shiny"],
    ["quest", "clamp"],
    ["newly", "braid"],
    ["shiny", "fault"],
    ["timid", "levee"],
    ["wield", "mayor"],
    ["stout", "welch"],
    ["modal", "fitch"],
    ["annoy", "timid"],
    ["vigor", "chuck"],
    ["gamma", "entry"],
    ["chunk", "rebel"],
    ["satin", "rouge"],
    ["pride", "awful"],
    ["tweed", "crush"],
    ["click", "upper"],
    ["hello", "squid"],
    ["dying", "check"],
    ["booty", "famed"],
    ["lobby", "shank"],
    ["glide", "chaff"],
    ["extra", "dimly"],
    ["sugar", "vomit"],
    ["karma", "spice"],
    ["flint", "grace"],
    ["whirl", "spade"],
    ["rifle", "boost"],
    ["hence", "boast"],
    ["repel", "smack"],
    ["weigh", "tract"],
    ["venue", "hilly"],
    ["fugue", "timid"],
    ["budge", "karma"],
    ["trail", "evoke"],
    ["brunt", "civil"],
    ["petit", "swarm"],
    ["knoll", "abide"],
    ["where", "flank"],
    ["power", "nasal"],
    ["foyer", "canal"],
    ["liter", "swamp"],
    ["dodge", "civil"],
    ["hazel", "grind"],
    ["purse", "gamma"],
    ["rinse", "laugh"],
    ["funny", "waive"],
    ["spoke", "gamut"],
    ["worry", "valet"],
    ["fuzzy", "depth"],
    ["flesh", "onion"],
    ["union", "bleed"],
    ["hello", "grind"],
    ["stage", "brook"],
    ["thigh", "comma"],
    ["ample", "snowy"],
    ["meter", "cling"],
    ["handy", "mixer"],
    ["purse", "woody"],
    ["aging", "cheek"],
    ["ardor", "filth"],
    ["thing", "small"],
    ["tribe", "smoky"],
    ["chart", "guise"],
    ["freak", "thumb"],
    ["peace", "fluid"],
    ["prove", "dummy"],
    ["creep", "dough"],
    ["stack", "owner"],
];

pub const INITIAL_GUESSES: [Word; 1000] = [
    b"build", b"fuzzy", b"prize", b"flint", b"heath", b"frank", b"group", b"rhyme", b"frock",
    b"print", b"lousy", b"beard", b"surge", b"whole", b"quote", b"notch", b"along", b"dwell",
    b"merit", b"plank", b"nurse", b"chess", b"shark", b"facet", b"leave", b"panic", b"forty",
    b"rebel", b"stock", b"etude", b"horse", b"least", b"vague", b"pizza", b"adieu", b"hedge",
    b"leach", b"mamma", b"mango", b"scent", b"chaff", b"manor", b"nymph", b"earth", b"gaudy",
    b"crews", b"cloud", b"horse", b"speak", b"plate", b"lunar", b"diver", b"chase", b"scarf",
    b"guide", b"waltz", b"solve", b"spook", b"snout", b"brush", b"bathe", b"haiku", b"point",
    b"hotel", b"nerve", b"modal", b"being", b"story", b"crude", b"grave", b"ocean", b"wight",
    b"sleep", b"angel", b"fives", b"green", b"drunk", b"taste", b"filth", b"voice", b"ditto",
    b"climb", b"adult", b"quick", b"image", b"merry", b"bonus", b"sixth", b"brain", b"fritz",
    b"color", b"pluck", b"mount", b"graft", b"racer", b"brews", b"drift", b"fault", b"chomp",
    b"surge", b"views", b"holly", b"milky", b"stare", b"brief", b"ozone", b"crown", b"slack",
    b"thump", b"lucky", b"lease", b"hence", b"gloop", b"above", b"usual", b"faint", b"waste",
    b"storm", b"shale", b"vocal", b"paint", b"daily", b"below", b"windy", b"alter", b"album",
    b"amiss", b"ethic", b"exist", b"cycle", b"gorge", b"nylon", b"decor", b"tithe", b"pizza",
    b"panda", b"madly", b"learn", b"cider", b"curry", b"papal", b"venus", b"plank", b"ozone",
    b"goose", b"jelly", b"silly", b"blond", b"death", b"share", b"hover", b"sense", b"sleep",
    b"puppy", b"early", b"dread", b"point", b"rhyme", b"eight", b"hydro", b"upper", b"vigil",
    b"elbow", b"zebra", b"flock", b"mouse", b"proof", b"music", b"night", b"pants", b"groom",
    b"charm", b"stick", b"actor", b"joint", b"shift", b"shrew", b"aandb", b"books", b"vapid",
    b"vegas", b"feast", b"melon", b"tiled", b"space", b"child", b"match", b"grays", b"stack",
    b"moral", b"mawed", b"windy", b"wound", b"cobol", b"atlas", b"beech", b"moose", b"cloud",
    b"sound", b"money", b"clock", b"vapor", b"miner", b"coral", b"water", b"snack", b"thump",
    b"witch", b"trick", b"creep", b"demon", b"snafu", b"night", b"treat", b"cycle", b"field",
    b"noise", b"sword", b"prime", b"cubed", b"vowel", b"devil", b"spoon", b"sound", b"space",
    b"swift", b"swift", b"force", b"under", b"point", b"dryer", b"party", b"toxic", b"tower",
    b"plant", b"dunes", b"chaos", b"beans", b"feast", b"broil", b"scale", b"sewer", b"vegas",
    b"joust", b"sport", b"silly", b"gaffe", b"pesto", b"cloud", b"comic", b"ocean", b"empty",
    b"craft", b"agent", b"crisp", b"masks", b"banks", b"labor", b"watch", b"birds", b"birds",
    b"birds", b"oopsy", b"atone", b"uturn", b"angel", b"white", b"sleep", b"trees", b"twist",
    b"lemon", b"brand", b"roses", b"cider", b"sleep", b"dance", b"horse", b"pluto", b"atoms",
    b"tired", b"socks", b"shore", b"spies", b"realm", b"crash", b"naked", b"reset", b"puppy",
    b"cyber", b"email", b"metal", b"scene", b"shrub", b"taste", b"medic", b"relax", b"vowel",
    b"swing", b"audit", b"guilt", b"green", b"spore", b"ennui", b"edgar", b"slash", b"grill",
    b"happy", b"money", b"money", b"toast", b"plant", b"store", b"drown", b"slang", b"grape",
    b"sneer", b"thorn", b"rhyme", b"gifts", b"trick", b"drwho", b"excel", b"grips", b"split",
    b"pansy", b"balls", b"jazzy", b"audio", b"seven", b"lines", b"opera", b"champ", b"grass",
    b"dates", b"radio", b"write", b"idiot", b"lungs", b"bloom", b"wheat", b"boots", b"vapid",
    b"duels", b"creep", b"juice", b"poker", b"japan", b"howls", b"scott", b"oops!", b"small",
    b"proof", b"stone", b"gummy", b"night", b"spicy", b"raves", b"digit", b"rugby", b"power",
    b"haunt", b"modem", b"delay", b"train", b"bravo", b"leave", b"micro", b"laity", b"micro",
    b"brisk", b"stray", b"tonal", b"hello", b"bowel", b"metro", b"ultra", b"ahead", b"evade",
    b"genre", b"jolly", b"wrist", b"award", b"abbot", b"cloak", b"arrow", b"blond", b"vague",
    b"broad", b"urban", b"guilt", b"awful", b"chile", b"rough", b"suite", b"aptly", b"grasp",
    b"power", b"throw", b"tease", b"orbit", b"money", b"strap", b"phone", b"block", b"light",
    b"think", b"patch", b"perch", b"cloud", b"excel", b"shook", b"rogue", b"ruler", b"vista",
    b"equip", b"heath", b"graft", b"bride", b"quick", b"alias", b"flask", b"noise", b"rouse",
    b"grate", b"chess", b"lower", b"chief", b"admit", b"rouge", b"chute", b"bully", b"bless",
    b"chili", b"joint", b"crime", b"night", b"amuse", b"print", b"probe", b"epoch", b"drove",
    b"shove", b"award", b"brine", b"using", b"flora", b"grove", b"elegy", b"maker", b"movie",
    b"karma", b"eerie", b"groom", b"sable", b"leech", b"speak", b"allow", b"refer", b"paste",
    b"bless", b"pulse", b"lapse", b"grail", b"cough", b"scare", b"leach", b"shook", b"debit",
    b"alter", b"plume", b"birch", b"finch", b"share", b"build", b"place", b"thick", b"viral",
    b"snail", b"three", b"cream", b"still", b"scout", b"truth", b"onion", b"super", b"valid",
    b"wight", b"tiger", b"fritz", b"otter", b"rouge", b"lunar", b"exact", b"spend", b"daily",
    b"price", b"would", b"suite", b"crowd", b"greed", b"dryer", b"novel", b"enter", b"queen",
    b"brood", b"speck", b"steam", b"serve", b"wield", b"reuse", b"brick", b"dough", b"prove",
    b"windy", b"melon", b"onion", b"staid", b"glaze", b"flint", b"exact", b"gloom", b"dance",
    b"stare", b"shaft", b"uncle", b"ethos", b"flair", b"prize", b"spill", b"sixth", b"found",
    b"birch", b"mirth", b"viral", b"toxin", b"brine", b"blind", b"rally", b"stone", b"layer",
    b"crush", b"irony", b"teach", b"vinyl", b"shout", b"crisp", b"tinge", b"snake", b"repay",
    b"snail", b"eerie", b"grail", b"haste", b"pious", b"water", b"forth", b"lousy", b"chess",
    b"steel", b"elite", b"terra", b"smear", b"table", b"bunny", b"frail", b"avert", b"tenth",
    b"which", b"stoic", b"havoc", b"edema", b"camel", b"shear", b"ankle", b"spicy", b"share",
    b"butte", b"cloak", b"paddy", b"lobby", b"exert", b"orbit", b"pause", b"mimic", b"spade",
    b"label", b"sugar", b"woody", b"magma", b"wager", b"demon", b"chill", b"aside", b"wield",
    b"steep", b"hardy", b"brave", b"fauna", b"torso", b"amuse", b"molar", b"dream", b"tally",
    b"molar", b"hairy", b"drake", b"spend", b"bulge", b"uncle", b"baker", b"issue", b"awful",
    b"field", b"tweed", b"chile", b"dryer", b"small", b"union", b"paint", b"night", b"axiom",
    b"lotus", b"widow", b"rusty", b"brave", b"alarm", b"penny", b"rusty", b"hello", b"vague",
    b"speak", b"syrup", b"sneer", b"avoid", b"winch", b"stoic", b"blind", b"prior", b"shrub",
    b"share", b"dying", b"array", b"seize", b"bully", b"debut", b"grand", b"blank", b"flood",
    b"spade", b"vivid", b"usher", b"rogue", b"envoy", b"gauze", b"plank", b"faint", b"sweet",
    b"shawl", b"amber", b"milky", b"tithe", b"micro", b"alert", b"drive", b"mouse", b"knife",
    b"olive", b"punch", b"vital", b"frost", b"bonus", b"bowel", b"metro", b"filth", b"anvil",
    b"later", b"melon", b"prize", b"truce", b"batch", b"steel", b"sixty", b"floor", b"stead",
    b"cloud", b"panel", b"slope", b"plank", b"debit", b"amend", b"gauze", b"baron", b"ovary",
    b"setup", b"blame", b"black", b"plate", b"pedal", b"petit", b"chick", b"coast", b"pivot",
    b"while", b"video", b"think", b"sheep", b"cover", b"tense", b"woody", b"blink", b"chick",
    b"speck", b"panel", b"cross", b"fitch", b"third", b"lance", b"shaft", b"steal", b"manor",
    b"diode", b"aisle", b"enemy", b"humor", b"witty", b"slate", b"sting", b"error", b"recur",
    b"braid", b"sling", b"taint", b"envoy", b"shave", b"least", b"those", b"award", b"short",
    b"lymph", b"skull", b"cable", b"pedal", b"witch", b"datum", b"value", b"quilt", b"birth",
    b"flame", b"chill", b"early", b"vicar", b"cover", b"winch", b"basil", b"logic", b"flour",
    b"react", b"drunk", b"toast", b"shalt", b"paint", b"heave", b"flesh", b"stead", b"bless",
    b"voice", b"kappa", b"cheer", b"field", b"pixel", b"waist", b"spine", b"hedge", b"youth",
    b"ready", b"prize", b"whose", b"video", b"sweep", b"gorge", b"creek", b"forte", b"where",
    b"login", b"sable", b"maker", b"chief", b"worth", b"seven", b"newly", b"clone", b"pizza",
    b"quill", b"frock", b"relic", b"ample", b"lodge", b"table", b"shock", b"fifty", b"bulge",
    b"oxide", b"aptly", b"snuff", b"sense", b"swine", b"undue", b"later", b"expel", b"chill",
    b"swift", b"cocoa", b"learn", b"bribe", b"chile", b"ionic", b"bluff", b"split", b"happy",
    b"micro", b"vicar", b"group", b"while", b"exact", b"shook", b"brisk", b"crypt", b"brick",
    b"proud", b"brood", b"stone", b"taste", b"worst", b"super", b"queer", b"canoe", b"rinse",
    b"mimic", b"avant", b"agree", b"house", b"setup", b"blaze", b"privy", b"lilac", b"anger",
    b"vista", b"prior", b"angel", b"coast", b"shear", b"chili", b"edema", b"marry", b"exile",
    b"irony", b"locus", b"slide", b"shady", b"clear", b"beach", b"motto", b"kappa", b"broad",
    b"jelly", b"paste", b"smoky", b"ready", b"groom", b"sting", b"agile", b"store", b"dress",
    b"crime", b"login", b"bloom", b"mixer", b"rouge", b"rugby", b"aback", b"major", b"incur",
    b"graft", b"aside", b"tough", b"fiery", b"tenet", b"haste", b"shark", b"level", b"madly",
    b"havoc", b"lover", b"thick", b"stone", b"cater", b"sauce", b"whose", b"aware", b"award",
    b"arson", b"swift", b"loose", b"cheap", b"stern", b"psalm", b"evade", b"tread", b"piece",
    b"scrub", b"tween", b"triad", b"creed", b"stand", b"rebel", b"alone", b"thief", b"first",
    b"where", b"villa", b"arbor", b"front", b"daddy", b"amend", b"mummy", b"cleft", b"spite",
    b"dogma", b"hello", b"shrub", b"curry", b"hobby", b"helix", b"avert", b"chaos", b"attic",
    b"thumb", b"saint", b"using", b"cruel", b"surge", b"relay", b"layer", b"refer", b"joint",
    b"amuse", b"bison", b"midst", b"basin", b"frown", b"obese", b"round", b"treat", b"mango",
    b"flint", b"stain", b"snout", b"moist", b"noble", b"winch", b"tenor", b"trans", b"nymph",
    b"flint", b"quill", b"shalt", b"build", b"spite", b"steep", b"polar", b"gamut", b"evoke",
    b"fitch", b"grant", b"radio", b"toxin", b"elder", b"glass", b"sperm", b"sharp", b"stare",
    b"virus", b"cling", b"siege", b"trend", b"yeast", b"above", b"mercy", b"famed", b"timer",
    b"fluid", b"shalt", b"chess", b"flint", b"devil", b"ready", b"swamp", b"blond", b"virus",
    b"green",
];
